name: Test and Deploy

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run Selected Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run specific tests
        run: |
          npx jest apps/backend/src/services/users/users.service.spec.ts
          npx jest apps/backend/src/services/tournament/tournament.service.spec.ts

  deploy:
    name: Deploy to DigitalOcean VPS
    runs-on: ubuntu-latest
    needs: test  # This ensures deployment only happens if tests pass

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: 34.171.196.79
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/Qilin
            
            git pull origin main

            docker compose down

            docker compose up -d --build
